global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'security'
    metrics_path: /metrics
    static_configs:
      - targets: ['security:3000']

  - job_name: 'uploader'
    metrics_path: /metrics
    static_configs:
      - targets: ['uploader:3000']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['storage:9000']
